# Generated by Django 4.2 on 2023-05-23 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(null=True, upload_to='film_posters')),
                ('studio', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('rating_IMDb', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
