# Generated by Django 4.2.1 on 2023-06-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studio_logo'),
        ('films', '0005_remove_film_publisher_remove_film_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='studios.studio', verbose_name='Студия'),
        ),
    ]
