# Generated by Django 4.2.1 on 2023-07-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
    ]
