# Generated by Django 4.2.1 on 2023-07-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.genre', verbose_name='Жанр'),
        ),
    ]
