# Generated by Django 4.2.1 on 2023-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_remove_film_genre_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='film',
            name='gross_worldwide',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
    ]
