# Generated by Django 4.2.1 on 2023-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_options_alter_actor_born_and_more'),
        ('films', '0014_film_budget_film_gross_worldwide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='stars',
        ),
        migrations.AddField(
            model_name='film',
            name='stars',
            field=models.ManyToManyField(to='actors.actor', verbose_name='Актеры'),
        ),
    ]
