# Generated by Django 4.2.1 on 2023-06-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studio_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
