# Generated by Django 4.2.1 on 2023-06-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
