# Generated by Django 4.2.1 on 2023-07-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='born',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='children',
            field=models.CharField(max_length=100, verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.FloatField(verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='main_site',
            field=models.URLField(max_length=100, verbose_name='Сайт актера'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя актера'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='poster',
            field=models.ImageField(null=True, upload_to='actor_posters', verbose_name='Фото'),
        ),
    ]
